### ISSUE TITLE
Ideas for supporting isize/usize

### ISSUE THREAD

**Issue by ckaran** [smessmer/binary-layout#7]
I know that it isn't safe to support `isize` or `usize` directly as their sizes change depending on the platform that the code runs on.  That said, it's still useful in some cases to be able to lay them out in memory.  I can see the following two methods of supporting them that aren't *too* horrible.

1. Feature gate the support, so that programmers need to opt into them.
2. Create `unsafe` versions of the appropriate traits that `isize`, `usize`, and anything else that is unsafe to implement can support.

I prefer the second option it's a lot easier to search for blocks of unsafe code and really verify them than to have some feature turned on that might be unsafe.  Would you be open to either of these ideas?

### Why I'm after this

I need a better/safer alternative to [abomonation](https://docs.rs/abomonation/0.7.3/abomonation/) that can handle cyclic data structures correctly.  Portability is less of a concern than speed (if I need to make it portable, I can add in a header that describes the sizes and layouts of primitive types held within, including any pointers).  I've already looked into a variety of serializers, and the closest I've found to what I need is [rkyv](https://crates.io/crates/rkyv), but in [talking with the author](https://github.com/rkyv/rkyv/issues/214), I've learned that cyclic data structures aren't supported, only DAGs.  All of the other serializers that I've found only support trees, or if they do support serializing DAGs and cyclic datastructures, do so at the cost of deserializing DAGs into trees (I'm looking at you [serde](https://serde.rs/feature-flags.html#-features-rc)).  In short, I want python's [pickle](https://docs.python.org/3/library/pickle.html), but for rust.  And since it doesn't appear to exist at the moment, I have to invent it.  `binary-layout` will likely be a low-level building block for it, assuming I can convince my boss to let me write it.

**Comment by smessmer** [comment]
Afaik, pickle is portable and, depending on the pickle version, achieves this by either always using i64, or by having a different type tag for i32 and i64. Does it work for your use case to just always use i64 when you want to store isize?

If you really need this, I'm ok with adding it but behind big warning banners. Can you give an example on how the API with unsafe would look like? I'm not sure if unsafe is the right approach since we don't really break rusts safety guarantees. A feature flag "nonportable-types" could work, but as you said, a marker in the type definition is better. Another idea that may work is a NonPortable wrapper that you need to write:

```rust
define_layout!(name, BigEndian, {
   field1: i8,
   field2: NonPortable<isize>,
}
```

Or maybe you need to add the marker to the general layout and if you don't, then those types are unavailable

```rust
define_layout!(name, BigEndian, NonPortable, {
   field1: i8,
   field2: isize,
}
```

**Comment by smessmer** [comment]
LayoutAs is a way to pre/post-process data while you're writing/reading it. In the memory, a `isize as u32` looks exactly like a `u32`, also respecting endianness of the layout. How truncation works is up to your `impl LayoutAs<u32> for usize` code.

**Comment by ckaran** [comment]
OK, so that sounds perfect!  Do you mind if I make a PR with the additions above?

**Comment by ckaran** [comment]
It's fine, I can add it to my own crate easily enough.  It just seemed like a simple way of adding in support for `isize`/`usize`, that's all.
